### ISSUE TITLE
In Acapulco Preparation, FeatureIDE functionality can be used to handle Complex Constraints

### ISSUE THREAD

**Issue by jabiercoding** [acapulco-spl/acapulco#1]
Complex constraints are removed in Acapulco Preparation. However, in some cases, complex constraints can be transformed in simple constraints. FeatureIDE functionality can be reused for this. In Feature IDE UI, when you right click a feature model, you can...
*  create a `Product-Equivalent Model without Complex Constraints`. The internal class is `de.ovgu.featureide.fm.core.conversion.ComplexConstraintConverter`. 
* `Export Feature Dependency Information` that uses the class `de.ovgu.featureide.fm.core.analysis.mig.ModalImplicationGraph`. An example of usage to get implies and excludes relations can be found in `de.ovgu.featureide.visualisation.ShowFeatureRelationsGraphCommandHandler` . Related publication: Krieter et al. ICSE 2018 Propagating Configuration Decisions with Modal Implication Graphs.

**Comment by jmhorcas** [comment]
Regarding the transformation of complex constraints:
Any complex constraint represented as a propositional logic (not, and, or, implies)  can be translated to simple constraints (requires, excludes). Related publication: [Knüppel et al. (Sec. 4.1)](https://dl.acm.org/doi/10.1145/3106237.3106252)
I don't know if FeatureIDE already implement this kind of transformations.

**Comment by szschaler** [comment]
This would be really cool to add support for...

Btw, what are these model implication graphs and how do they relate to our feature-activation diagrams?

**Comment by jabiercoding** [comment]
@jmhorcas The first option is implemented by Alexander Knüppel and in their publication they mention that the prototype was in FeatureIDE so it should be this one. We should check if they have tests or do some tests ourselves.

@szschaler Regarding model implication graphs and this reference, we included a discussion on that in the Acapulco TSE paper.

**Comment by szschaler** [comment]
Many thanks

**Comment by jabiercoding** [comment]
The Knüppel conversion was integrated. If the transformation is trivial (all complex constraints are pseudo complex constraints) then it is performed directly, if the transformation requires creating synthetic features, the users get a warning to choose if they want to create those features or if they want to ignore it, in this second case all the complex constraints will be removed and the user will know through the message that this may lead to potentially invalid configs.
