### ISSUE TITLE
If the user does not want to transform complex constraints, an evolution objective can be to minimize non-satisfied constraints

### ISSUE THREAD

**Issue by jabiercoding** [acapulco-spl/acapulco#2]
The user will need to configure the objective by providing the path to a feature model that includes these complex constraints (right now complex constraints are removed during Acapulco preparation).

**Comment by szschaler** [comment]
Nice idea!

**Comment by jabiercoding** [comment]
Instead of counting the unsatisfied constraints, the new Valid Configuration objective returns 1 when the configuration is valid, and 0 when it is invalid. It was not straightforward to actually count the unsatisfied constraints, and it can be a time-expensive task. The implemented boolean objective is an alternative to this, and it helps the users to keep track of which are the useful solutions when applying their target objectives.
