### ISSUE TITLE
Incorrect generated CPCOs for one case?

### ISSUE THREAD

**Issue by jabiercoding** [acapulco-spl/acapulco#4]
If we have this model
```
namespace MySPL

features
	MySPL {abstract}	
		optional
			A
			B
			C

constraints
	A & B => C
```
the Knuppel method to convert complex constraints obtain this model
```
namespace MySPL

features
	MySPL	
		optional
			A
			B
			C

		mandatory
			Subtree	
				mandatory
					OR0_0	
						or
							A_1_1
							B_2_1
							C_3_1

constraints
	!A_1_1 | !A
	!B_2_1 | !B
	!C_3_1 | C
```
Then, once the CPCOs are generated, these rules seem wrong as not(A) or not(B) is an excludes relation
```
Rule Act_A_1_1
Node A_1_1: false->true
```
and 
```
Rule Act_A
Node A: false->true
Node A_1_1: true
```
It seems that the CPCO generation is interpreting `!A_1_1 | !A` as `not(A) or A_1_1` which is `A implies A_1_1`.  The same happens for the second constraint, while the rules for the features of the third seems correct.

**Comment by szschaler** [comment]
This might well be a naming issue. I have a vague recollection that there was an issue with underscores in names in the past…

Could you chuck this into the test harness in class `acapulco.activationdiagrams.ActivationDiagramTest` (you should be able to add it to the `exploreSpecificFeature` method) and see what it does?

**Comment by jabiercoding** [comment]
I checked that there is no problem with the underscores. Finally the problem was with a refactoring I made and the parsing of some constraints. Now fixed.
